# Generated by Django 5.1.4 on 2025-02-07 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_es', models.CharField(max_length=255)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_es', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_public', models.BooleanField(default=True)),
                ('product_type', models.CharField(choices=[('weapon_melee', 'Melee Weapon'), ('weapon_ranged', 'Ranged Weapon'), ('shield', 'Shield'), ('armor_light', 'Light Armor'), ('armor_heavy', 'Heavy Armor'), ('potion_health', 'Health Potion'), ('potion_mana', 'Mana Potion'), ('scroll', 'Magic Scroll'), ('enchanted_item', 'Enchanted Item'), ('food', 'Food'), ('drink', 'Drink'), ('herb', 'Herb'), ('tool', 'Tool'), ('mount', 'Mount')], max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_es', models.TextField(blank=True, null=True)),
                ('store_type', models.CharField(choices=[('general_store', 'General Store'), ('market_stall', 'Market Stall'), ('blacksmith', 'Blacksmith'), ('alchemist', 'Alchemist'), ('magic_shop', 'Magic Shop'), ('herbalist', 'Herbalist'), ('tailor', 'Tailor'), ('inn', 'Inn'), ('tavern', 'Tavern'), ('stable', 'Stable'), ('fletcher', 'Fletcher')], max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dndstores.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dndstores.store')),
            ],
            options={
                'unique_together': {('store', 'product')},
            },
        ),
    ]
